// ========
// Imports
// ========

import { z } from 'zod';


// ====================
// Validation Schemas
// ====================

// UserRole Input Validation
export const usersSchema = z.object({

    // id = UUID, PK are automatically generated by the database
    email: z.string().email({ message: "Invalid Email Address"}),
    fullname: z.string().min(2, {message: "Full Name Must Be At Least 2 Characters Long"}),
    avatar_url: z.string().url({ message: "Invalid URL Format"}).optional().or(z.literal('')), // Must be a valid URL or just Empty
    role: z.enum(['admin', 'supervisor', 'student'],  {message: "Role Must Be One Of: 'admin', 'supervisor', 'student'"}), // Ensures that this matches UserRole Alias
    created_at: z.string().datetime().optional() // ISO Date String, Default Time .Now() on creation

})

// Task Input Validation
export const taskSchema = z.object({

    // id = UUID, PK are automatically generated by the database
    title: z.string().min(3, {message: "Title Must Be At Least 3 Characters Long"}),
    description: z.string().min(3, {message: "Description Must Be At Least 3 Characters Long"}),
    assigned_to: z.string().uuid({ message: "Assigned To Must Be A Valid UUID from Users Table"}),
    status: z.enum(['to-do', 'in-progress', 'review', 'completed'], {message: "Status Must Be One Of: 'to-do', 'in-progress', 'review', 'completed'"}), // Ensures that this matches TaskStatus Alias
    priority: z.enum(['low', 'medium', 'high'], {message: "Priority Must Be One Of: 'low', 'medium', 'high'"}), // Ensures that this matches TaskPriority Alias
    due_date: z.string().datetime({ message: "Due Date Must Be A Valid ISO Date Time String"}),
    created_by: z.string().uuid({ message: "Created By Must Be A Valid UUID from Users Table"}),
    created_at: z.string().datetime().optional() // ISO Date String Default Time .Now() on Creation


})


// Attendance Input Validation
export const attendanceSchema = z.object({

     // id = UUID, PK are automatically generated by the database
    user_id: z.string().uuid({ message: "User ID Must Be A Valid UUID from Users Table"}),
    date: z.string().datetime(), // ISO Date String
    time_in: z.string().datetime(), // ISO Date String
    time_out: z.string().datetime().nullable(), // ISO Date String, A Null Box to Allow for Cases Where Intern Forgets to Clock Out or is Still Clocked In
    total_hours: z.number().nonnegative({ message: "Total Hours Must Be a Positive Number"}).nullable(), // Total Hours Can Be Null Initially Until Time Out is Recorded, Then It Must Be A Positive Number
    status: z.enum(['present', 'absent', 'late', 'excused'], { message: "Status Must Be One Of: 'present', 'absent', 'late', 'excused'"}), // Ensures that this matches AttendanceStatus Alias
    created_at: z.string().datetime().optional() // ISO Date String Default Time .Now() on Creation

})


// Announcements Input Validation
export const announcementSchema = z.object({

    // id = UUID, PK are automatically generated by the database
    title: z.string().min(3, { message: "Title Must Be At Least 3 Characters Long"}),
    content: z.string().min(3, { message: "Content Must Be At Least 3 Characters Long"}),
    created_by: z.string().uuid({ message: "Created By Must Be A Valid UUID from Users Table"}),
    visibility: z.enum(['all', 'admin', 'supervisor', 'student'], { message: "Visibility Must Be One Of: 'all', 'admin', 'supervisor', 'student'"}), // Ensures that this matches UserRole Alias
    created_at: z.string().datetime().optional() // ISO Date String Default Time .Now() on Creation

})


// Evaluations Input Validation
export const evaluationSchema = z.object({

    // id = UUID, PK are automatically generated by the database
    intern_id: z.string().uuid({ message: "Intern ID Must Be A Valid UUID From Users Table WHERE Role = 'student'"}),
    supervisor_id: z.string().uuid({ message: "Supervisor ID Must Be A Valid UUID From Users Table WHERE Role = 'supervisor'"}),
    score: z.number().min(1, { message: "Score Must Be At Least 1"}).max(10, {message: "Score Cannot Be Greater Than 10"}),
    feedback: z.string().min(3, { message: "Feedback Must Be At Least 3 Characters Long"}),
    evaluation_date: z.string().datetime({ message: "Evaluation Date Must Be A Valid ISO Date Time String"}),
    created_at: z.string().datetime().optional() // ISO Date String Default Time .Now() on Creation


})